# Generated by Django 5.0.3 on 2024-04-30 10:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_atrakcji', models.CharField(default='Atrakcja', max_length=50)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(max_length=50)),
                ('cena_podstawowa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('wiek_min', models.IntegerField()),
                ('wiek_max', models.IntegerField()),
                ('godzina_otwarcia', models.TimeField()),
                ('godzina_zamkniecia', models.TimeField()),
                ('czas_na_zwiedzanie', models.PositiveIntegerField()),
                ('obraz', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('plec', models.CharField(max_length=10)),
                ('wiek', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
                ('nr_tel', models.CharField(max_length=15)),
                ('haslo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Znizka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_znizki', models.CharField(max_length=30)),
                ('mnoznik', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Adres_atrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=50)),
                ('Miasto', models.CharField(max_length=50)),
                ('Kod_pocztowy', models.CharField(max_length=10)),
                ('Ulica', models.CharField(max_length=50)),
                ('Nr_budynku', models.CharField(max_length=50)),
                ('Nr_lokalu', models.CharField(max_length=50)),
                ('id_atrakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.atrakcja')),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_koncowa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('id_atrakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.atrakcja')),
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_planu', models.CharField(max_length=30)),
                ('data_utworzenia', models.DateField()),
                ('cena_koncowa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Atrakcje_w_planie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atrakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.atrakcja')),
                ('id_planu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plan')),
                ('id_znizki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.znizka')),
            ],
        ),
    ]
