# Generated by Django 5.0.3 on 2024-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrakcja',
            name='obraz',
            field=models.URLField(default='', max_length=300),
        ),
    ]
