# Generated by Django 5.0.4 on 2024-04-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_klient_haslo_klient_is_active_klient_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Koszyk',
        ),
    ]
