# Generated by Django 5.0.4 on 2024-04-30 22:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_koszyk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_koncowa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('id_atrakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.atrakcja')),
            ],
        ),
    ]
