# Generated by Django 5.0.4 on 2024-04-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_koszyk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
