# Generated by Django 5.0.4 on 2024-04-30 22:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_klient_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klient',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
