# Generated by Django 5.0.3 on 2024-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_koszyk_id_klienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrakcja',
            name='opis',
            field=models.TextField(max_length=250),
        ),
    ]
