# Generated by Django 5.0.3 on 2024-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_atrakcja_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='koszyk',
            name='ilosc',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='atrakcja',
            name='opis',
            field=models.TextField(max_length=1100),
        ),
    ]
