# Generated by Django 5.0.4 on 2024-05-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_koszyk_ilosc_alter_atrakcja_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrakcja',
            name='obraz',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.CreateModel(
            name='PrzypisanieAtrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.atrakcja')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='atrakcje',
            field=models.ManyToManyField(through='mainapp.PrzypisanieAtrakcji', to='mainapp.atrakcja'),
        ),
        migrations.DeleteModel(
            name='Atrakcje_w_planie',
        ),
    ]
