# Generated by Django 5.0.3 on 2024-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_atrakcja_obraz_przypisanieatrakcji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cena_koncowa',
        ),
        migrations.AddField(
            model_name='plan',
            name='obraz',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
