# Generated by Django 5.0.3 on 2024-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_plan_cena_koncowa_plan_obraz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('nazwa_kategorii', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
