# Generated by Django 5.0.3 on 2024-05-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrakcja',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kategorie'),
        ),
    ]
