# Generated by Django 5.0.3 on 2024-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_atrakcja_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='opis_planu',
            field=models.TextField(default='', max_length=1100),
        ),
    ]
