# Generated by Django 5.0.3 on 2024-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_plan_opis_planu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='opis_planu',
            field=models.TextField(max_length=1100),
        ),
    ]
