# Generated by Django 5.0.3 on 2024-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_plan_opis_planu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nazwa_planu',
            field=models.CharField(max_length=50),
        ),
    ]
